### PR TITLE
Add jquery.tinymce.js non-minified file version

### PR DESCRIPTION
**Pull request by carlosagsmendes**
The project doesn't have a non-minified version of jquery.tinymce.js. When using package managers like JSPM and Webpack we end up having to minify the provided minified version and that process is very slow.

### CODE REVIEW

**Comment by spocke** [comment]
I will include this in the build script. Closing this one since this repo is for distribution only.

**Comment by carlosagsmendes** [comment]
Thank you @spocke. Could you please check if the plugins non-minified files are being updated?

For example, the advlist files appear to be from different versions: 

Autosize

**Comment by spocke** [comment]
It there wasn't any change to that particular plugin then it won't be updated since the diff would be 0 lines. The minified file would still be updated though.

**Comment by carlosagsmendes** [comment]
Got it. Thanks for the clarification

**Pull request closed without merging**
